image: alpine:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache nodejs nodejs-npm git python g++ make
    - npm install -g yarn
    - yarn --registry http://167.99.243.81:4873/
    - yarn build
  retry: 1

docker-build:
  stage: package
  image: docker:dind
  script:
  - docker info
  - docker build -t $CI_REGISTRY_IMAGE .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE
  retry: 1
  only:
    - master

deploy:
  stage: deploy
  script:
  - apk add --update --no-cache openssh sshpass
  - ./deploy.sh $DO_PASS
  retry: 1
  only:
    - master