image: alpine:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache nodejs nodejs-npm git python g++ make
    - npm install -g yarn
    - yarn --registry http://167.99.243.81:4873/
    - yarn build
  only:
    - develop

docker-debug-build:
  stage: package
  image: docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:dev-latest -f ./docker/debug/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

deploy-test:
  stage: deploy
  environment: test
  script:
    - apk add --update --no-cache openssh sshpass
    - ./deploy.sh $DO_PASS
  only:
    - master

docker-release-build:
  stage: package
  environment: production
  image: docker:dind
  only:
    - tags
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -f ./docker/release/Dockerfile .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

deploy-prod:
  stage: deploy
  environment: production
  image: google/cloud-sdk
  tags:
    - kubernetes
  script:
    - kubectl config set-cluster cash36-production-cluster --server="$K8S_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-ci --token=$K8S_TOKEN
    - kubectl config set-context default --cluster=cash36-production-cluster --user=gitlab-ci --namespace=element36-io
    - kubectl config use-context default
    - kubectl set image deployment/cash36-frontend cash36-frontend=registry.gitlab.com/cash36/cash36-frontend:$CI_COMMIT_REF_NAME
    - kubectl rollout status deployment/cash36-frontend
  only:
    - tags
  when: manual