image: alpine:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache nodejs nodejs-npm git python g++ make
    - npm install -g yarn
    - yarn --registry http://167.99.243.81:4873/
    - yarn build
  retry: 1
  except:
    - tags

docker-debug-build:
  stage: package
  image: docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:dev-latest -f ./docker/debug/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  retry: 1
  only:
    - master

deploy-debug-build:
  stage: deploy
  environment: test
  script:
    - apk add --update --no-cache openssh sshpass
#    - ./deploy.sh $DO_PASS
  only:
    - master

docker-release-build:
  stage: package
  environment: production
  image: docker:dind
  only:
    - tags
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -f ./docker/release/Dockerfile .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  retry: 1

deploy:
  stage: deploy
  environment: production
  image: google/cloud-sdk
  script:
#    - kubectl config set-cluster $KUBE_NAME --server="$KUBE_URL" --insecure-skip-tls-verify=true
#    - kubectl config set-credentials cluster-admin --username="$KUBE_USER" --password="$KUBE_PASSWORD"
#    - kubectl config set-context default --cluster=$KUBE_NAME --user=cluster-admin
#    - kubectl config use-context default
    - kubectl set image deployment/cash36-frontend cash36-frontend=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} \
        --namespace="element36-io" \
        --insecure-skip-tls-verify=true
    - kubectl rollout status deployment/cash36-frontend
  retry: 1
  only:
    - tags
  when: manual