  image: alpine:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apk add --no-cache nodejs nodejs-npm git python g++ make
    - npm install -g yarn
    - yarn --registry http://167.99.243.81:4873/
    - yarn build
  retry: 1

deploy to dev:
  environment: dev
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=cash36-frontend --api-key=$HEROKU_API_KEY
  retry: 1
  only:
    - develop

deploy to test:
  environment: test
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=cash36-test-frontend --api-key=$HEROKU_API_KEY
  retry: 1
  only:
    - master