image: alpine:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
  - build
  - package
  - deploy

build:
  stage: build
  script:
    - echo "building..."
#    - apk add --no-cache nodejs nodejs-npm git python g++ make
#    - npm install -g yarn
#    - yarn --registry http://167.99.243.81:4873/
#    - yarn build
  retry: 1
  only:
    - develop

docker-debug-build:
  stage: package
  image: docker:dind
  script:
#    - docker build -t $CI_REGISTRY_IMAGE:dev-latest -f ./docker/debug/Dockerfile .
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker push $CI_REGISTRY_IMAGE
  retry: 1
  only:
    - master

deploy-test:
  stage: deploy
  environment: test
  image: lachlanevenson/k8s-kubectl:latest
  script:
#    - apk add --update --no-cache openssh sshpass
#    - ./deploy.sh $DO_PASS
    - kubectl apply -f 02_cash36-frontend.yml
    - kubectl apply -f 03_ingress_service.yml
    - kubectl rollout status deployment/cash36-frontend
  only:
    - master

docker-release-build:
  stage: package
  environment: production
  image: docker:dind
  only:
    - tags
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -f ./docker/release/Dockerfile .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  retry: 1

deploy-prod:
  stage: deploy
  environment: production
  image: lachlanevenson/k8s-kubectl:latest
  tags:
    - kubernetes
  script:
    - kubectl apply -f 02_cash36-frontend.yml
    - kubectl apply -f 03_ingress_service.yml
    - kubectl rollout status deployment/cash36-frontend
  retry: 1
  only:
    - tags
  when: manual