// AUTHENTICATION


// USER
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_ATTESTED = 'USER_ATTESTED'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'

// NOTIFICATION
export const INIT_NOTIFICATIONS_REQUEST = 'INIT_NOTIFICATIONS_REQUEST'
export const INIT_NOTIFICATIONS_SUCCESS = 'INIT_NOTIFICATIONS_SUCCESS'
export const INIT_NOTIFICATIONS_ERROR = 'INIT_NOTIFICATIONS_ERROR'

export const NEW_NOTIFICATION = 'NEW_NOTIFICATION'
export const UPDATE_BADGE_COUNT = 'UPDATE_BADGE_COUNT'

// TOKEN
export const UPDATE_TOKENS_REQUEST = 'UPDATE_TOKENS_REQUEST'
export const UPDATE_TOKENS_SUCCESS = 'UPDATE_TOKENS_SUCCESS'
export const UPDATE_TOKENS_ERROR = 'UPDATE_TOKENS_ERROR'
