export const GET_WALLETS = 'GET_WALLETS';
export const REMOVE_WALLET = 'REMOVE_WALLET';
export const UPDATE_WALLET_DESCRIPTION = 'UPDATE_WALLET_DESCRIPTION';
export const SET_MAIN_WALLET = 'SET_MAIN_WALLET';
