export const AUTH_USER = 'AUTH_USER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const ATTESTATION_PROGRESS = 'ATTESTATION_PROGRESS';
export const CONFIRM_ATTESTATION = 'CONFIRM_ATTESTATION';
export const GET_CURRENT_KYC_STEP = 'GET_CURRENT_KYC_STEP';
