// USER
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// NOTIFICATION
export const INIT_NOTIFICATIONS = 'INIT_NOTIFICATIONS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const RESET_BADGE_COUNT = 'RESET_BADGE_COUNT';

// TOKEN
export const UPDATE_TOKENS = 'UPDATE_TOKENS';