# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@element36-io'
      - name: Install dependencies
        run: yarn install build:rinkeby build:mainnet
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}     
     
     
    

